### ISSUE TITLE
Tor Browser: medium and standard safety setting users: issues with logo placement

### ISSUE THREAD

**Issue by okaysoraya** [EFForg/starttls-frontend#152]
The logo seems to be kind of obtrusive in the standard size of Tor Browser, on the medium and standard safety settings. Could we fix it so it scales appropriately to this standard Tor Browser window size? 

![screen shot 2018-06-11 at 10 16 22 am](https://user-images.githubusercontent.com/16709499/41246895-408da380-6d61-11e8-91d2-2c37c9e2495c.png)
![screen shot 2018-06-11 at 10 16 13 am](https://user-images.githubusercontent.com/16709499/41246897-40a666c2-6d61-11e8-8e7d-c7e4a3c8cc49.png)
![screen shot 2018-06-11 at 10 15 58 am](https://user-images.githubusercontent.com/16709499/41246898-40c2c376-6d61-11e8-841e-760269a928c9.png)
![screen shot 2018-06-11 at 10 15 45 am](https://user-images.githubusercontent.com/16709499/41246899-40de1248-6d61-11e8-8429-0e3c2db5c666.png)

**Comment by lschatzkin** [comment]
I am not seeing this issue on Tor, in either Linux or Mac versions.
