### ISSUE TITLE
Improve alignment of policy list widget

### ISSUE THREAD

**Issue by vbrown608** [EFForg/starttls-frontend#213]
The widget about adding a domain to the policy list has some alignment issues in Chromium. My first choice would be to work with a designer to rework this widget to make it more web friendly - it's currently a select element that's replaced with divs using javascript to allow more flexible styling, but I think it would be good to use a real, more lightly styled select element or get rid of the dropdown menu metaphor altogether.

Desktop: 
![manage-alignment-desktop](https://user-images.githubusercontent.com/1887071/43932807-facbde7a-9bfa-11e8-8b23-75652c20b93f.png)

Mobile:
![manage-alignment-mobile](https://user-images.githubusercontent.com/1887071/43932808-faf7cb8e-9bfa-11e8-8c71-5bfb28b0ea59.png)

**Comment by vbrown608** [comment]
We have new mockups for this! Thanks @okaysoraya :grinning:

See Mattermost for the latest version

**Comment by lschatzkin** [comment]
https://xd.adobe.com/view/fdec87de-44bd-42b4-7d3e-2e4857e437d8-8bdd/screen/a10c5ecd-de78-47ab-8cb0-9dbeb0c49879/StartTLS-Almost-there-result-2
