### ISSUE TITLE
Reduce logo size?

### ISSUE THREAD

**Issue by lschatzkin** [EFForg/starttls-frontend#237]
Check in with Hugh about this.

**Comment by lschatzkin** [comment]
@okaysoraya I checked in with Hugh and it seems we are seeing the logo on the current site as the same size as your mockup. Did you want it even smaller? The form is appearing above the fold from what we see.

**Comment by okaysoraya** [comment]
Hi Laura!
On a smaller screen (e.g. 13” MacBook), this isn’t the case for a standard browser. Here’s what it looks like on my computer. Any chance we can do a little bit of tweaking to ensure that it looks like the mockup for folks with smaller screen sizes?
Thanks,
Soraya

**Comment by lschatzkin** [comment]
@okaysoraya Can you reattach your screenshot? I'm testing on a loaner mac I have but still not seeing the problem. Thanks!

**Comment by lschatzkin** [comment]
<img width="1437" alt="small-mac-screen" src="https://user-images.githubusercontent.com/852512/50927332-46b5e680-140c-11e9-89d6-de84b08a2d66.png">

@okaysoraya The problem with this example is that the size of elements are determined by the width of the browser. In this case, the browser is wide (even though the screen is short from top to bottom), so it will display the larger logo.

When I spoke earlier this week to @hughillustration , he said that he'd rather keep the logo the size it is now but is open to discussion.
