### ISSUE TITLE
No IE11 support for URL api

### ISSUE THREAD

**Issue by vbrown608** [EFForg/starttls-frontend#261]
We should parse params from the query string another way or use a polyfill :(

**Comment by rubicae** [comment]
I've created branches to explore each of these possibilities: [parsing query params by hand](https://github.com/EFForg/starttls-frontend/compare/master...rubicae:ie11-no-URL) and [using a polyfill](https://github.com/EFForg/starttls-frontend/compare/master...rubicae:url-polyfill-IE11).  Any thoughts on what the best route would be?

**Comment by sydneyli** [comment]
Thanks @rubicae ! Polyfill seem like the canonical way to fix URL compatibility issues like these -- feel free to submit a PR! I'd rather avoid rolling custom parsing code where possible.
